train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ../liif/load/div2k/DIV2K_train_HR
      repeat: 40
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled-cascaded
    args:
      inp_size: 48
      batch_size: 32
      scale_min:
      - 1
      scale_max:
      - 4
      sample_q: 2304
      augment: true
      phase: train
      k: 1
  batch_size: 32
val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ../liif/load/div2k/DIV2K_valid_HR
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled-cascaded
    args:
      inp_size: 48
      batch_size: 32
      scale_min:
      - 4
      scale_max:
      - 4
      sample_q: 2304
      phase: valid
  batch_size: 32
data_norm:
  inp:
    sub:
    - 0.5
    div:
    - 0.5
  gt:
    sub:
    - 0.5
    div:
    - 0.5
model:
  name: clit
  args:
    base_dim: 256
    head: 8
    r: 3
    imnet_num: 1
    conv_num: 1
    is_cell: true
    local_attn: true
    encoder_spec:
      name: edsr-baseline
      args:
        no_upsampling: true
    pb_spec:
      name: posenc
      args:
        posenc_type: sinusoid
        posenc_scale: 10
        hidden_dims: 64
        enc_dims: 64
        gamma: 1
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list:
        - 256
        - 256
        - 256
        - 256
        act: gelu
optimizer:
  name: adam
  args:
    lr: 0.0001
epoch_max: 1000
multi_step_lr:
  milestones:
  - 200
  - 400
  - 600
  - 800
  gamma: 0.5
epoch_val: 1
epoch_save: 100
resume: null
pre_train: null
