train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ../../../mngo_datasets/load/div2k/DIV2K_train_HR
      #root_path2: ../../../mngo_datasets/load/Flickr2K/Flickr2K_HR
      repeat: 80
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled-collate-batch
    args:
      inp_sizes: [48]
      augment: true
      sample_q: 2304
      # sample_patch: true
      # limit_scale: 4 # change scale_min
      scale_min: 1
      # scale_max: 4
      crop_from_edges: true
      # sample_from_edges: true
      plot_scales: true
  collate_batch: true
  batch_size: 64

gradient_accumulation_steps: 1

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ../../../mngo_datasets/load/div2k/DIV2K_valid_HR
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled-collate-batch
    args:
      inp_sizes: [48]
      augment: true
      sample_q: 2304
      # limit_scale: 3
      scale_min: 1
      scale_max: 4
  collate_batch: true
  batch_size: 64

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}
  # inp_scale_max: 48

model:
  name: lte
  args:
    encoder_spec:
      name: swinir
      args:
        no_upsampling: true
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [256, 256, 256]
    hidden_dim: 256
    # scale_aware_phase: true
    # scale_aware_mlp: true

optimizer:
  name: adam
  args:
    lr: 1.e-4
multi_step_lr:
  milestones: [500000, 800000, 900000, 950000]
  gamma: 0.5

resume: save/_train_swinir-baseline-lte-variable-input-div2k-final_sample-2304-scale-1toMax-inputs-48-div2k-edge-crop-batch-64/iteration-800000.pth

iter_val: 100000
iter_save: 100000
iter_max: 1000000