train_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ./load/celebAHQ/64
      root_path_2: ./load/celebAHQ/1024
      split_file: ./load/celebAHQ/split.json
      split_key: train
      cache: bin # in-memory
  wrapper:
    name: sr-implicit-uniform-varied # resizes output image for training
    args:
      size_min: 64
      size_max: 1024
      sample_q: 2048
      augment: true
  batch_size: 16

val_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ./load/celebAHQ/64
      root_path_2: ./load/celebAHQ/1024
      split_file: ./load/celebAHQ/split.json
      split_key: val
      first_k: 100
      cache: bin
  wrapper:
    name: sr-implicit-paired
    args: {}
      # sample_q: 1024
  batch_size: 4

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: liif_glean_styleganv2
  args:
    in_size: 64
    out_size: 1024
    style_channels: 512
    generator_spec:
      name: stylegan2
      args:
        out_size: 1024
        style_channels: 512
      sd: ckpts/stylegan2/stylegan2-ffhq-config-f-official_20210327_171224-bce9310c.pth # path downloaded from https://github.com/open-mmlab/mmediting/blob/master/configs/restorers/glean/glean_in128out1024_4x2_300k_ffhq_celebahq.py
      # ckpts/stylegan2/550000.pt
      # ckpts/stylegan2/stylegan2-cat-config-f-official_20210327_172444-15bc485b.pth
      # ckpts/stylegan2/stylegan2-ffhq-config-f-official_20210327_171224-bce9310c.pth
      prefix: 'generator_ema'
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [256, 256, 256, 256]

optimizer:
  name: adam
  args:
    # lower base lr with pre-trained stylegan2
    lr: 1.e-4
epoch_max: 200
multi_step_lr:
  milestones: [50]
  gamma: 0.1

epoch_val: 1
epoch_save: 50
