train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./load/div2k/DIV2K_train_HR
      first_k: 10
      repeat: 1
      #cache: in_memory
      # sharded: true
  wrapper:
    name: sr-implicit-downsampled-collate-batch
    args:
      inp_sizes: [48]
      augment: true
      sample_q: 2304
      sample_patch: true
      # limit_scale: 4 # change scale_min
      scale_min: 1
      scale_max: 1
      plot_scales: true
      crop_from_edges: true
      sample_from_edges: true
  collate_batch: true
  batch_size: 1

gan_based: true

gradient_accumulation_steps: 1

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./load/div2k/DIV2K_valid_HR
      first_k: 10
      repeat: 16
      # cache: in_memory
  wrapper:
    name: sr-implicit-downsampled-collate-batch
    args:
      inp_sizes: [48]
      augment: true
     # sample_q: 2304
      # sample_patch: true
      # limit_scale: 3
      scale_min: 1
      scale_max: 4
  collate_batch: true
  batch_size: 1

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}
  # inp_scale_max: 64

model:
  name: lte
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        no_upsampling: true
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [256, 256, 256]
    hidden_dim: 256
    # scale_aware_phase: true
    # scale_aware_mlp: true

model_D:
  name: unet-discriminator
  args: {}

optimizer:
  name: adam
  args:
    lr: 1.e-4
multi_step_lr:
  milestones: [200000, 400000, 600000, 800000]
  gamma: 0.5

optimizer_D:
  name: adam
  args:
    lr: 1.e-4
multi_step_lr_D:
  milestones: [200000, 400000, 600000, 800000]
  gamma: 0.5

resume: save_iter/_train_edsr-baseline-lte-variable-input-patch-gan-test_test2/iteration-50.pth
resume_D: save_iter/_train_edsr-baseline-lte-variable-input-patch-gan-test_test2/d_iteration-50.pth

iter_max: 1000000
iter_val: 10
iter_save: 10