train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./load/div2k/DIV2K_train_HR
      # root_path2: ./load/Flickr2K/Flickr2K_HR # change repeat
      repeat: 20
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled-collate-batch
    args:
      inp_sizes: [60]
      augment: true
      sample_q: 7200
      # limit_scale: 4 # change scale_min
      scale_min: 4
      plot_scales: true
  collate_batch: true
  batch_size: 16

gradient_accumulation_steps: 1

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./load/div2k/DIV2K_valid_HR
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled-collate-batch
    args:
      inp_sizes: [60]
      sample_q: 7200
      limit_scale: 4
  collate_batch: true
  batch_size: 16

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: liif
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        no_upsampling: true
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [256, 256, 256, 256, 256, 256]

optimizer:
  name: adam
  args:
    lr: 5.e-5
epoch_max: 500
multi_step_lr:
  milestones: [100, 200, 300, 400] # [200, 400, 600, 800]
  gamma: 0.5

pretrained: ckpts/edsr-baseline-liif-six-layers.pth # change lr

epoch_val: 1
epoch_save: 200
