train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ../../../mngo_datasets/load/DIV8K/train
      repeat: 10
      cache: in_memory
      sharded: true
      # edge_map: true
  wrapper:
    name: sr-implicit-downsampled-collate-batch
    args:
      inp_sizes: [48]
      augment: true
      sample_q: 2304
      # limit_scale: 3 # change scale_min
      scale_min: 1
      scale_max: 4
      crop_from_edges: true
      plot_scales: true
  collate_batch: true
  batch_size: 32

gradient_accumulation_steps: 1

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ../../../mngo_datasets/load/div2k/DIV2K_valid_HR
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled-collate-batch
    args:
      inp_sizes: [48]
      augment: true
      sample_q: 2304
      # limit_scale: 3
      scale_min: 1
      scale_max: 4
  collate_batch: true
  batch_size: 32

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}
  # inp_scale_max: 64

model:
  name: lte
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        no_upsampling: true
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [256, 256, 256]
    hidden_dim: 256
    # scale_aware_phase: true
    # scale_aware_mlp: true

optimizer:
  name: adam
  args:
    lr: 1.e-4
iter_max: 1000000
multi_step_lr:
  milestones: [200000, 400000, 600000, 800000]
  gamma: 0.5

iter_val: 100000
iter_save: 100000