train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ../../../mngo_datasets/load/LSDIR/train/HR
      repeat: 1
      #cache: in_memory
      sharded: true
  wrapper:
    name: sr-implicit-downsampled-collate-batch
    args:
      inp_sizes: [48]
      augment: true
      sample_q: 2304
      sample_patch: true
      # limit_scale: 4 # change scale_min
      scale_min: 1
      plot_scales: true
      crop_from_edges: true
      sample_from_edges: true
  collate_batch: true
  batch_size: 128

gan_based: true

gradient_accumulation_steps: 1

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ../../../mngo_datasets/load/div2k/DIV2K_valid_HR
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled-collate-batch
    args:
      inp_sizes: [48]
      augment: true
      sample_q: 2304
      # limit_scale: 3
      scale_min: 1
      scale_max: 4
  collate_batch: true
  batch_size: 128

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}
  # inp_scale_max: 48

model:
  name: lte
  args:
    encoder_spec:
      name: swinir
      args:
        no_upsampling: true
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [256, 256, 256]
    hidden_dim: 256
    # scale_aware_phase: true
    # scale_aware_mlp: true

model_D:
  name: unet-discriminator
  args: {}

loss_fn: huber

optimizer:
  name: adam
  args:
    lr: 1.e-4
multi_step_lr:
  milestones: [50000, 100000, 150000, 200000]
  gamma: 0.5

optimizer_D:
  name: adam
  args:
    lr: 1.e-4
multi_step_lr_D:
  milestones: [50000, 100000, 150000, 200000]
  gamma: 0.5

# same gan, same lpips
l_adv: 1
l_fm: 0.01
l_lpips: 1

pretrained: save/_train_swinir-baseline-lte-variable-input-flickr2k_sample-2304-scale-1toMax-inputs-48-flickr2k-batch-64-resume/iteration-999000.pth

iter_val: 25000
iter_save: 25000
iter_max: 250000